# Generated by Django 4.0 on 2021-12-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=4048)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
